In [302]:
import numpy as np
import keras
from keras.utils import to_categorical

How to decode information received from a noisy channel?

In [16]:
adaptation_data = np.concatenate((np.random.normal(3, 0.3, 20), np.random.normal(2,0.3, 20), np.random.normal(1,0.3,20),
                                 np.random.normal(0, 0.3, 20), np.random.normal(-1, 0.3, 20),np.random.normal(-2, 0.3, 20),
                                 np.random.normal(-3, 0.3, 20)))

true_answers = np.concatenate((np.repeat(3, 20), np.repeat(2, 20), np.repeat(1, 20), np.repeat(0, 20),
                              np.repeat(-1, 20), np.repeat(-2, 20), np.repeat(-3, 20)))

In [273]:
# as first layer in a sequential model:
model = keras.Sequential()
model.add(keras.layers.Dense(7, input_shape=(1,), kernel_regularizer=keras.regularizers.l2(0.5), 
                             activity_regularizer = keras.regularizers.l2(0.01)))
model.add(keras.layers.Dense(1, kernel_regularizer=keras.regularizers.l2(0.2)))
model.add(keras.layers.Dense(1, kernel_regularizer=keras.regularizers.l2(0.2)))
# now the model will take as input arrays of shape (*, 16)
# and output arrays of shape (*, 32)

In [274]:
model.compile(loss='mean_squared_error', optimizer= 'adam')

In [275]:
#sgd = keras.optimizers.SGD(lr=0.005)

model.fit(adaptation_data, true_answers, epochs=600, batch_size=10)

Epoch 1/600
140/140 [==============================] - 0s 132us/step - loss: 7.4911
Epoch 2/600
140/140 [==============================] - 0s 128us/step - loss: 6.9943
Epoch 3/600
140/140 [==============================] - 0s 132us/step - loss: 6.5501
Epoch 4/600
140/140 [==============================] - 0s 179us/step - loss: 6.1597
Epoch 5/600
140/140 [==============================] - 0s 135us/step - loss: 5.8117
Epoch 6/600
140/140 [==============================] - 0s 197us/step - loss: 5.5039
Epoch 7/600
140/140 [==============================] - 0s 136us/step - loss: 5.2030
Epoch 8/600
140/140 [==============================] - 0s 138us/step - loss: 4.9427
Epoch 9/600
140/140 [==============================] - 0s 144us/step - loss: 4.6895
Epoch 10/600
140/140 [==============================] - 0s 146us/step - loss: 4.4270
Epoch 11/600
140/140 [==============================] - 0s 154us/step - loss: 4.1794
Epoch 12/600
140/140 [==============================] - 0s 106us/step - lo

140/140 [==============================] - 0s 92us/step - loss: 1.0655
Epoch 98/600
140/140 [==============================] - 0s 108us/step - loss: 1.0638
Epoch 99/600
140/140 [==============================] - 0s 130us/step - loss: 1.0617
Epoch 100/600
140/140 [==============================] - 0s 144us/step - loss: 1.0604
Epoch 101/600
140/140 [==============================] - 0s 95us/step - loss: 1.0583
Epoch 102/600
140/140 [==============================] - 0s 100us/step - loss: 1.0568
Epoch 103/600
140/140 [==============================] - 0s 121us/step - loss: 1.0552
Epoch 104/600
140/140 [==============================] - 0s 115us/step - loss: 1.0537
Epoch 105/600
140/140 [==============================] - 0s 122us/step - loss: 1.0522
Epoch 106/600
140/140 [==============================] - 0s 145us/step - loss: 1.0508
Epoch 107/600
140/140 [==============================] - 0s 99us/step - loss: 1.0498
Epoch 108/600
140/140 [==============================] - 0s 114us/step - 

140/140 [==============================] - 0s 139us/step - loss: 1.0231
Epoch 193/600
140/140 [==============================] - 0s 133us/step - loss: 1.0234
Epoch 194/600
140/140 [==============================] - 0s 127us/step - loss: 1.0227
Epoch 195/600
140/140 [==============================] - 0s 132us/step - loss: 1.0240
Epoch 196/600
140/140 [==============================] - 0s 131us/step - loss: 1.0229
Epoch 197/600
140/140 [==============================] - 0s 122us/step - loss: 1.0230
Epoch 198/600
140/140 [==============================] - 0s 145us/step - loss: 1.0229
Epoch 199/600
140/140 [==============================] - 0s 122us/step - loss: 1.0229
Epoch 200/600
140/140 [==============================] - 0s 121us/step - loss: 1.0236
Epoch 201/600
140/140 [==============================] - 0s 117us/step - loss: 1.0241
Epoch 202/600
140/140 [==============================] - 0s 119us/step - loss: 1.0228
Epoch 203/600
140/140 [==============================] - 0s 122us/st

140/140 [==============================] - 0s 112us/step - loss: 1.0228
Epoch 288/600
140/140 [==============================] - 0s 125us/step - loss: 1.0233
Epoch 289/600
140/140 [==============================] - 0s 114us/step - loss: 1.0227
Epoch 290/600
140/140 [==============================] - 0s 122us/step - loss: 1.0229
Epoch 291/600
140/140 [==============================] - 0s 110us/step - loss: 1.0233
Epoch 292/600
140/140 [==============================] - 0s 119us/step - loss: 1.0229
Epoch 293/600
140/140 [==============================] - 0s 143us/step - loss: 1.0230
Epoch 294/600
140/140 [==============================] - 0s 110us/step - loss: 1.0233
Epoch 295/600
140/140 [==============================] - 0s 100us/step - loss: 1.0227
Epoch 296/600
140/140 [==============================] - 0s 102us/step - loss: 1.0227
Epoch 297/600
140/140 [==============================] - 0s 118us/step - loss: 1.0228
Epoch 298/600
140/140 [==============================] - 0s 158us/st

140/140 [==============================] - 0s 109us/step - loss: 1.0232
Epoch 383/600
140/140 [==============================] - 0s 126us/step - loss: 1.0229
Epoch 384/600
140/140 [==============================] - 0s 138us/step - loss: 1.0231
Epoch 385/600
140/140 [==============================] - 0s 129us/step - loss: 1.0230
Epoch 386/600
140/140 [==============================] - 0s 111us/step - loss: 1.0227
Epoch 387/600
140/140 [==============================] - 0s 92us/step - loss: 1.0238
Epoch 388/600
140/140 [==============================] - 0s 136us/step - loss: 1.0230
Epoch 389/600
140/140 [==============================] - 0s 122us/step - loss: 1.0229
Epoch 390/600
140/140 [==============================] - 0s 128us/step - loss: 1.0234
Epoch 391/600
140/140 [==============================] - 0s 165us/step - loss: 1.0228
Epoch 392/600
140/140 [==============================] - 0s 133us/step - loss: 1.0230
Epoch 393/600
140/140 [==============================] - 0s 143us/ste

140/140 [==============================] - 0s 107us/step - loss: 1.0229
Epoch 478/600
140/140 [==============================] - 0s 101us/step - loss: 1.0231
Epoch 479/600
140/140 [==============================] - 0s 116us/step - loss: 1.0228
Epoch 480/600
140/140 [==============================] - 0s 124us/step - loss: 1.0232
Epoch 481/600
140/140 [==============================] - 0s 107us/step - loss: 1.0232
Epoch 482/600
140/140 [==============================] - 0s 128us/step - loss: 1.0228
Epoch 483/600
140/140 [==============================] - 0s 95us/step - loss: 1.0227
Epoch 484/600
140/140 [==============================] - 0s 121us/step - loss: 1.0227
Epoch 485/600
140/140 [==============================] - 0s 110us/step - loss: 1.0230
Epoch 486/600
140/140 [==============================] - 0s 121us/step - loss: 1.0227
Epoch 487/600
140/140 [==============================] - 0s 114us/step - loss: 1.0228
Epoch 488/600
140/140 [==============================] - 0s 112us/ste

140/140 [==============================] - 0s 113us/step - loss: 1.0238
Epoch 573/600
140/140 [==============================] - 0s 103us/step - loss: 1.0229
Epoch 574/600
140/140 [==============================] - 0s 132us/step - loss: 1.0233
Epoch 575/600
140/140 [==============================] - 0s 115us/step - loss: 1.0229
Epoch 576/600
140/140 [==============================] - 0s 111us/step - loss: 1.0228
Epoch 577/600
140/140 [==============================] - 0s 100us/step - loss: 1.0229
Epoch 578/600
140/140 [==============================] - 0s 116us/step - loss: 1.0228
Epoch 579/600
140/140 [==============================] - 0s 160us/step - loss: 1.0233
Epoch 580/600
140/140 [==============================] - 0s 168us/step - loss: 1.0231
Epoch 581/600
140/140 [==============================] - 0s 123us/step - loss: 1.0231
Epoch 582/600
140/140 [==============================] - 0s 98us/step - loss: 1.0228
Epoch 583/600
140/140 [==============================] - 0s 129us/ste

In [276]:
predictions = model.predict(adaptation_data)

In [277]:
adaptation_data

array([ 2.96651108,  2.84336865,  2.62039018,  2.687272  ,  3.03021518,
        3.0984753 ,  3.00531105,  3.30687184,  3.10592146,  2.86120472,
        3.41424403,  3.16292981,  2.81278728,  3.68566561,  2.77295831,
        3.16579207,  3.37903288,  2.98918157,  2.63992968,  2.87288558,
        2.2747632 ,  1.54300596,  2.30650283,  1.67722103,  1.79591512,
        1.92793773,  2.64469981,  2.23283142,  1.52783337,  1.95524363,
        2.28306565,  2.11703625,  1.5332547 ,  2.42775864,  1.48616502,
        1.86374154,  2.08861239,  1.99303598,  1.87681957,  2.13724662,
        0.75183297,  1.04303039,  0.87657224,  1.20651375,  1.35235572,
        1.05533013,  0.98298844,  1.21517471,  1.609013  ,  1.03653301,
        1.09978949,  1.05205301,  0.7940305 ,  0.70877494,  1.50523773,
        1.09226171,  0.91423281,  1.03711761,  1.02993469,  0.81797284,
        0.00783391, -0.52373327, -0.01251965, -0.19837256, -0.15739775,
        0.37416519,  0.5153504 , -0.11214994,  0.0148494 ,  0.10

In [278]:
predictions

array([[ 2.6500297e+00],
       [ 2.5396008e+00],
       [ 2.3396428e+00],
       [ 2.3996196e+00],
       [ 2.7071569e+00],
       [ 2.7683699e+00],
       [ 2.6848242e+00],
       [ 2.9552515e+00],
       [ 2.7750473e+00],
       [ 2.5555956e+00],
       [ 3.0515382e+00],
       [ 2.8261702e+00],
       [ 2.5121768e+00],
       [ 3.2949378e+00],
       [ 2.4764595e+00],
       [ 2.8287370e+00],
       [ 3.0199623e+00],
       [ 2.6703596e+00],
       [ 2.3571651e+00],
       [ 2.5660703e+00],
       [ 2.0296986e+00],
       [ 1.3734889e+00],
       [ 2.0581615e+00],
       [ 1.4938476e+00],
       [ 1.6002876e+00],
       [ 1.7186798e+00],
       [ 2.3614428e+00],
       [ 1.9920959e+00],
       [ 1.3598830e+00],
       [ 1.7431667e+00],
       [ 2.0371439e+00],
       [ 1.8882558e+00],
       [ 1.3647443e+00],
       [ 2.1668987e+00],
       [ 1.3225164e+00],
       [ 1.6611112e+00],
       [ 1.8627663e+00],
       [ 1.7770571e+00],
       [ 1.6728393e+00],
       [ 1.9063796e+00],


In [279]:
adaptation_trial = np.random.normal(3, 0.3, 5)

adaptation_true_answers = np.repeat(3, 5)

test_trial = np.array([0])

In [280]:
model.fit(adaptation_trial, adaptation_true_answers, epochs=300, batch_size=5)

Epoch 1/300
5/5 [==============================] - 0s 587us/step - loss: 1.0236
Epoch 2/300
5/5 [==============================] - 0s 298us/step - loss: 1.0219
Epoch 3/300
5/5 [==============================] - 0s 240us/step - loss: 1.0193
Epoch 4/300
5/5 [==============================] - 0s 275us/step - loss: 1.0160
Epoch 5/300
5/5 [==============================] - 0s 240us/step - loss: 1.0126
Epoch 6/300
5/5 [==============================] - 0s 291us/step - loss: 1.0092
Epoch 7/300
5/5 [==============================] - 0s 243us/step - loss: 1.0063
Epoch 8/300
5/5 [==============================] - 0s 240us/step - loss: 1.0040
Epoch 9/300
5/5 [==============================] - 0s 220us/step - loss: 1.0023
Epoch 10/300
5/5 [==============================] - 0s 302us/step - loss: 1.0012
Epoch 11/300
5/5 [==============================] - 0s 1ms/step - loss: 1.0007
Epoch 12/300
5/5 [==============================] - 0s 291us/step - loss: 1.0005
Epoch 13/300
5/5 [=====================

Epoch 103/300
5/5 [==============================] - 0s 210us/step - loss: 0.9265
Epoch 104/300
5/5 [==============================] - 0s 198us/step - loss: 0.9258
Epoch 105/300
5/5 [==============================] - 0s 150us/step - loss: 0.9250
Epoch 106/300
5/5 [==============================] - 0s 201us/step - loss: 0.9242
Epoch 107/300
5/5 [==============================] - 0s 183us/step - loss: 0.9234
Epoch 108/300
5/5 [==============================] - 0s 204us/step - loss: 0.9226
Epoch 109/300
5/5 [==============================] - 0s 258us/step - loss: 0.9219
Epoch 110/300
5/5 [==============================] - 0s 1ms/step - loss: 0.9211
Epoch 111/300
5/5 [==============================] - 0s 246us/step - loss: 0.9203
Epoch 112/300
5/5 [==============================] - 0s 205us/step - loss: 0.9195
Epoch 113/300
5/5 [==============================] - 0s 209us/step - loss: 0.9188
Epoch 114/300
5/5 [==============================] - 0s 208us/step - loss: 0.9180
Epoch 115/300
5/5 

Epoch 203/300
5/5 [==============================] - 0s 442us/step - loss: 0.8526
Epoch 204/300
5/5 [==============================] - 0s 237us/step - loss: 0.8519
Epoch 205/300
5/5 [==============================] - 0s 252us/step - loss: 0.8512
Epoch 206/300
5/5 [==============================] - 0s 263us/step - loss: 0.8505
Epoch 207/300
5/5 [==============================] - 0s 264us/step - loss: 0.8498
Epoch 208/300
5/5 [==============================] - 0s 252us/step - loss: 0.8491
Epoch 209/300
5/5 [==============================] - 0s 281us/step - loss: 0.8484
Epoch 210/300
5/5 [==============================] - 0s 445us/step - loss: 0.8477
Epoch 211/300
5/5 [==============================] - 0s 237us/step - loss: 0.8470
Epoch 212/300
5/5 [==============================] - 0s 228us/step - loss: 0.8463
Epoch 213/300
5/5 [==============================] - 0s 207us/step - loss: 0.8456
Epoch 214/300
5/5 [==============================] - 0s 209us/step - loss: 0.8449
Epoch 215/300
5/

In [281]:
predictions = model.predict(adaptation_trial)

In [282]:
predictions

array([[3.022233 ],
       [2.8717825],
       [2.9486964],
       [2.8910234],
       [2.7612174]], dtype=float32)

In [283]:
adaptation_trial

array([3.29711927, 3.03783037, 3.17038515, 3.07099055, 2.84728029])

In [284]:
model.predict(test_trial)

array([[1.1091046]], dtype=float32)

classifier

In [390]:
adaptation_data = np.concatenate((np.random.normal(3, 0.3, 20), np.random.normal(2,0.3, 20), np.random.normal(1,0.3,20),
                                 np.random.normal(0, 0.3, 20), np.random.normal(-1, 0.3, 20),np.random.normal(-2, 0.3, 20),
                                 np.random.normal(-3, 0.3, 20)))

true_classes = np.concatenate((np.repeat(0, 20), np.repeat(1, 20), np.repeat(2, 20), np.repeat(3, 20),
                              np.repeat(4, 20), np.repeat(5, 20), np.repeat(6, 20)))

true_classes_oh = to_categorical(true_classes)
print(true_classes_oh)


[[1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0.

In [391]:
# invert encoding
inverted = np.argmax(true_classes_oh, axis = 1)
print(inverted)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 3 3 3 3 3 3 3 3 3 3 3 3 3 3
 3 3 3 3 3 3 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 4 5 5 5 5 5 5 5 5 5 5 5
 5 5 5 5 5 5 5 5 5 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6 6]


In [425]:
classifier = keras.Sequential()
classifier.add(keras.layers.Dense(3, input_shape=(1,)))
classifier.add(keras.layers.Dense(7, init='uniform'))
classifier.add(keras.layers.Activation('sigmoid'))
               

/home/marina/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(7, kernel_initializer="uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


In [438]:
sgd = keras.optimizers.SGD(lr=0.05, decay=1e-6, momentum=0.9, nesterov=True)
classifier.compile(loss='binary_crossentropy', optimizer=sgd)

In [439]:
classifier.fit(adaptation_data, true_classes_oh, epochs=1000, batch_size=50)

Epoch 1/1000
140/140 [==============================] - 0s 32us/step - loss: 0.4138
Epoch 2/1000
140/140 [==============================] - 0s 62us/step - loss: 0.3668
Epoch 3/1000
140/140 [==============================] - 0s 38us/step - loss: 0.3236
Epoch 4/1000
140/140 [==============================] - 0s 37us/step - loss: 0.2887
Epoch 5/1000
140/140 [==============================] - 0s 28us/step - loss: 0.2757
Epoch 6/1000
140/140 [==============================] - 0s 66us/step - loss: 0.2783
Epoch 7/1000
140/140 [==============================] - 0s 53us/step - loss: 0.2830
Epoch 8/1000
140/140 [==============================] - 0s 27us/step - loss: 0.2820
Epoch 9/1000
140/140 [==============================] - 0s 37us/step - loss: 0.2775
Epoch 10/1000
140/140 [==============================] - 0s 58us/step - loss: 0.2740
Epoch 11/1000
140/140 [==============================] - 0s 43us/step - loss: 0.2724
Epoch 12/1000
140/140 [==============================] - 0s 34us/step - lo

140/140 [==============================] - 0s 28us/step - loss: 0.2717
Epoch 98/1000
140/140 [==============================] - 0s 33us/step - loss: 0.2717
Epoch 99/1000
140/140 [==============================] - 0s 33us/step - loss: 0.2723
Epoch 100/1000
140/140 [==============================] - 0s 66us/step - loss: 0.2720
Epoch 101/1000
140/140 [==============================] - 0s 43us/step - loss: 0.2718
Epoch 102/1000
140/140 [==============================] - 0s 32us/step - loss: 0.2718
Epoch 103/1000
140/140 [==============================] - 0s 37us/step - loss: 0.2718
Epoch 104/1000
140/140 [==============================] - 0s 104us/step - loss: 0.2719
Epoch 105/1000
140/140 [==============================] - 0s 35us/step - loss: 0.2716
Epoch 106/1000
140/140 [==============================] - 0s 29us/step - loss: 0.2718
Epoch 107/1000
140/140 [==============================] - 0s 43us/step - loss: 0.2718
Epoch 108/1000
140/140 [==============================] - 0s 37us/step

140/140 [==============================] - 0s 94us/step - loss: 0.2718
Epoch 193/1000
140/140 [==============================] - 0s 41us/step - loss: 0.2719
Epoch 194/1000
140/140 [==============================] - 0s 78us/step - loss: 0.2718
Epoch 195/1000
140/140 [==============================] - 0s 47us/step - loss: 0.2719
Epoch 196/1000
140/140 [==============================] - 0s 60us/step - loss: 0.2716
Epoch 197/1000
140/140 [==============================] - 0s 66us/step - loss: 0.2721
Epoch 198/1000
140/140 [==============================] - 0s 40us/step - loss: 0.2717
Epoch 199/1000
140/140 [==============================] - 0s 31us/step - loss: 0.2717
Epoch 200/1000
140/140 [==============================] - 0s 51us/step - loss: 0.2715
Epoch 201/1000
140/140 [==============================] - 0s 42us/step - loss: 0.2721
Epoch 202/1000
140/140 [==============================] - 0s 38us/step - loss: 0.2716
Epoch 203/1000
140/140 [==============================] - 0s 38us/ste

140/140 [==============================] - 0s 35us/step - loss: 0.2717
Epoch 288/1000
140/140 [==============================] - 0s 46us/step - loss: 0.2714
Epoch 289/1000
140/140 [==============================] - 0s 27us/step - loss: 0.2713
Epoch 290/1000
140/140 [==============================] - 0s 30us/step - loss: 0.2717
Epoch 291/1000
140/140 [==============================] - 0s 30us/step - loss: 0.2715
Epoch 292/1000
140/140 [==============================] - 0s 28us/step - loss: 0.2720
Epoch 293/1000
140/140 [==============================] - 0s 32us/step - loss: 0.2719
Epoch 294/1000
140/140 [==============================] - 0s 28us/step - loss: 0.2713
Epoch 295/1000
140/140 [==============================] - 0s 25us/step - loss: 0.2715
Epoch 296/1000
140/140 [==============================] - 0s 27us/step - loss: 0.2716
Epoch 297/1000
140/140 [==============================] - 0s 28us/step - loss: 0.2713
Epoch 298/1000
140/140 [==============================] - 0s 29us/ste

140/140 [==============================] - 0s 31us/step - loss: 0.2714
Epoch 383/1000
140/140 [==============================] - 0s 30us/step - loss: 0.2712
Epoch 384/1000
140/140 [==============================] - 0s 77us/step - loss: 0.2713
Epoch 385/1000
140/140 [==============================] - 0s 40us/step - loss: 0.2712
Epoch 386/1000
140/140 [==============================] - 0s 37us/step - loss: 0.2715
Epoch 387/1000
140/140 [==============================] - 0s 41us/step - loss: 0.2714
Epoch 388/1000
140/140 [==============================] - 0s 28us/step - loss: 0.2717
Epoch 389/1000
140/140 [==============================] - 0s 43us/step - loss: 0.2712
Epoch 390/1000
140/140 [==============================] - 0s 32us/step - loss: 0.2713
Epoch 391/1000
140/140 [==============================] - 0s 40us/step - loss: 0.2712
Epoch 392/1000
140/140 [==============================] - 0s 46us/step - loss: 0.2718
Epoch 393/1000
140/140 [==============================] - 0s 43us/ste

140/140 [==============================] - 0s 31us/step - loss: 0.2712
Epoch 478/1000
140/140 [==============================] - 0s 29us/step - loss: 0.2714
Epoch 479/1000
140/140 [==============================] - 0s 31us/step - loss: 0.2714
Epoch 480/1000
140/140 [==============================] - 0s 28us/step - loss: 0.2714
Epoch 481/1000
140/140 [==============================] - 0s 25us/step - loss: 0.2712
Epoch 482/1000
140/140 [==============================] - 0s 26us/step - loss: 0.2716
Epoch 483/1000
140/140 [==============================] - 0s 32us/step - loss: 0.2711
Epoch 484/1000
140/140 [==============================] - 0s 28us/step - loss: 0.2718
Epoch 485/1000
140/140 [==============================] - 0s 56us/step - loss: 0.2712
Epoch 486/1000
140/140 [==============================] - 0s 28us/step - loss: 0.2719
Epoch 487/1000
140/140 [==============================] - 0s 28us/step - loss: 0.2715
Epoch 488/1000
140/140 [==============================] - 0s 26us/ste

140/140 [==============================] - 0s 24us/step - loss: 0.2712
Epoch 573/1000
140/140 [==============================] - 0s 24us/step - loss: 0.2710
Epoch 574/1000
140/140 [==============================] - 0s 28us/step - loss: 0.2713
Epoch 575/1000
140/140 [==============================] - 0s 30us/step - loss: 0.2711
Epoch 576/1000
140/140 [==============================] - 0s 38us/step - loss: 0.2718
Epoch 577/1000
140/140 [==============================] - 0s 34us/step - loss: 0.2713
Epoch 578/1000
140/140 [==============================] - 0s 32us/step - loss: 0.2712
Epoch 579/1000
140/140 [==============================] - 0s 31us/step - loss: 0.2712
Epoch 580/1000
140/140 [==============================] - 0s 27us/step - loss: 0.2715
Epoch 581/1000
140/140 [==============================] - 0s 25us/step - loss: 0.2711
Epoch 582/1000
140/140 [==============================] - 0s 71us/step - loss: 0.2719
Epoch 583/1000
140/140 [==============================] - 0s 36us/ste

140/140 [==============================] - 0s 28us/step - loss: 0.2716
Epoch 668/1000
140/140 [==============================] - 0s 25us/step - loss: 0.2716
Epoch 669/1000
140/140 [==============================] - 0s 43us/step - loss: 0.2710
Epoch 670/1000
140/140 [==============================] - 0s 30us/step - loss: 0.2714
Epoch 671/1000
140/140 [==============================] - 0s 33us/step - loss: 0.2712
Epoch 672/1000
140/140 [==============================] - 0s 31us/step - loss: 0.2710
Epoch 673/1000
140/140 [==============================] - 0s 34us/step - loss: 0.2710
Epoch 674/1000
140/140 [==============================] - 0s 28us/step - loss: 0.2710
Epoch 675/1000
140/140 [==============================] - 0s 25us/step - loss: 0.2714
Epoch 676/1000
140/140 [==============================] - 0s 28us/step - loss: 0.2718
Epoch 677/1000
140/140 [==============================] - 0s 107us/step - loss: 0.2711
Epoch 678/1000
140/140 [==============================] - 0s 37us/st

140/140 [==============================] - 0s 30us/step - loss: 0.2713
Epoch 763/1000
140/140 [==============================] - 0s 56us/step - loss: 0.2710
Epoch 764/1000
140/140 [==============================] - 0s 40us/step - loss: 0.2709
Epoch 765/1000
140/140 [==============================] - 0s 40us/step - loss: 0.2712
Epoch 766/1000
140/140 [==============================] - 0s 79us/step - loss: 0.2713
Epoch 767/1000
140/140 [==============================] - 0s 36us/step - loss: 0.2714
Epoch 768/1000
140/140 [==============================] - 0s 80us/step - loss: 0.2714
Epoch 769/1000
140/140 [==============================] - 0s 38us/step - loss: 0.2709
Epoch 770/1000
140/140 [==============================] - 0s 53us/step - loss: 0.2713
Epoch 771/1000
140/140 [==============================] - 0s 65us/step - loss: 0.2715
Epoch 772/1000
140/140 [==============================] - 0s 85us/step - loss: 0.2713
Epoch 773/1000
140/140 [==============================] - 0s 41us/ste

140/140 [==============================] - 0s 54us/step - loss: 0.2710
Epoch 858/1000
140/140 [==============================] - 0s 33us/step - loss: 0.2711
Epoch 859/1000
140/140 [==============================] - 0s 63us/step - loss: 0.2711
Epoch 860/1000
140/140 [==============================] - 0s 35us/step - loss: 0.2717
Epoch 861/1000
140/140 [==============================] - 0s 53us/step - loss: 0.2711
Epoch 862/1000
140/140 [==============================] - 0s 100us/step - loss: 0.2720
Epoch 863/1000
140/140 [==============================] - 0s 60us/step - loss: 0.2710
Epoch 864/1000
140/140 [==============================] - 0s 54us/step - loss: 0.2709
Epoch 865/1000
140/140 [==============================] - 0s 53us/step - loss: 0.2709
Epoch 866/1000
140/140 [==============================] - 0s 88us/step - loss: 0.2712
Epoch 867/1000
140/140 [==============================] - 0s 59us/step - loss: 0.2709
Epoch 868/1000
140/140 [==============================] - 0s 47us/st

140/140 [==============================] - 0s 32us/step - loss: 0.2713
Epoch 953/1000
140/140 [==============================] - 0s 68us/step - loss: 0.2708
Epoch 954/1000
140/140 [==============================] - 0s 40us/step - loss: 0.2728
Epoch 955/1000
140/140 [==============================] - 0s 49us/step - loss: 0.2710
Epoch 956/1000
140/140 [==============================] - 0s 57us/step - loss: 0.2709
Epoch 957/1000
140/140 [==============================] - 0s 66us/step - loss: 0.2709
Epoch 958/1000
140/140 [==============================] - 0s 37us/step - loss: 0.2710
Epoch 959/1000
140/140 [==============================] - 0s 36us/step - loss: 0.2711
Epoch 960/1000
140/140 [==============================] - 0s 44us/step - loss: 0.2707
Epoch 961/1000
140/140 [==============================] - 0s 42us/step - loss: 0.2710
Epoch 962/1000
140/140 [==============================] - 0s 41us/step - loss: 0.2712
Epoch 963/1000
140/140 [==============================] - 0s 37us/ste

In [440]:
np.argmax(classifier.predict(adaptation_data), axis = 1)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2,
       2, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 2, 4,
       3, 4, 3, 3, 2, 3, 3, 3, 3, 3, 3, 4, 3, 4, 5, 4, 4, 4, 4, 5, 4, 4,
       4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 6, 5, 5, 5,
       5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6, 6, 5, 6, 6, 6, 6,
       6, 6, 6, 6, 6, 6, 6, 6])

In [444]:
adaptation_trial = np.random.normal(-3, 0.3, 2)

adaptation_true_answers = np.repeat(6, 2)
adaptation_true_answers_oh = to_categorical(adaptation_true_answers)

test_trial = np.array([0])

In [445]:
np.argmax(classifier.predict(test_trial), axis = 1)

array([3])

In [485]:
classifier.fit(adaptation_trial, adaptation_true_answers_oh, epochs=5, batch_size=2)

Epoch 1/5
2/2 [==============================] - 0s 523us/step - loss: 2.5340e-04
Epoch 2/5
2/2 [==============================] - 0s 533us/step - loss: 2.5243e-04
Epoch 3/5
2/2 [==============================] - 0s 563us/step - loss: 2.5146e-04
Epoch 4/5
2/2 [==============================] - 0s 431us/step - loss: 2.5050e-04
Epoch 5/5
2/2 [==============================] - 0s 491us/step - loss: 2.4955e-04


In [486]:
np.argmax(classifier.predict(adaptation_trial), axis = 1)

array([6, 6])

Contrastive illusion!

In [484]:
np.argmax(classifier.predict(test_trial), axis = 1)

array([2])